services:
  nginx:
    build:
      context: requirements/nginx
      args:
        ALPINE_TAG: ${ALPINE_TAG}
    image: nginx:v1
    container_name: nginx
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "set -e; nginx -t >/dev/null 2>&1 && ip=$$(hostname -i | awk '{print $$1}') && nc -z -w2 $$ip 443"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - wp_files:/var/www/html:ro
      - static_site:/var/www/static
    networks: 
      intra:
        aliases:
          - ${DOMAIN}
    pull_policy: never

  wordpress:
    build:
      context: requirements/wordpress
      args:
        ALPINE_TAG: ${ALPINE_TAG}
        WP_VERSION: ${WP_VERSION}
        WPCLI_VERSION: ${WPCLI_VERSION}
    image: wordpress:v1
    container_name: wordpress
    restart: always
    environment:
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_TABLE_PREFIX: ${WP_TABLE_PREFIX}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      DB_HOST: mariadb
      DB_NAME: ${WP_DB_NAME}
      DB_USER: ${WP_DB_USER}
      USER_EMAIL: ${WP_USER_EMAIL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      SMTP_HOST: mailpit
      SMTP_PORT: ${MAILPIT_SMTP_PORT}
      DOMAIN: ${DOMAIN}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    secrets:
      - wp_db_password
      - wp_admin_password
      - wp_user_password
      - redis_password
    healthcheck:
      test: ["CMD-SHELL", "php-fpm84 -t >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - wp_files:/var/www/html
    networks: [intra]
    pull_policy: never

  mariadb:
    build:
      context: requirements/mariadb
      args:
        ALPINE_TAG: ${ALPINE_TAG}
    image: mariadb:v1
    container_name: mariadb
    restart: always
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
    secrets:
      - wp_db_password
      - mariadb_root_password
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --protocol=socket --socket=/run/mysqld/mysqld.sock -uroot -p$$(cat /run/secrets/mariadb_root_password) ping --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - wp_db:/var/lib/mysql
    networks: [intra]
    pull_policy: never

  redis:
    build:
      context: requirements/redis
      args:
        ALPINE_TAG: ${ALPINE_TAG}
    image: redis:v1
    container_name: redis
    restart: always
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 -p ${REDIS_PORT} -a $$(cat /run/secrets/redis_password) ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks: [intra]
    pull_policy: never
    volumes:
      - redis_data:/data
    
  ftp:
    build:
      context: requirements/ftp
      args:
        ALPINE_TAG: ${ALPINE_TAG}
    image: ftp:v1
    container_name: ftp
    restart: always
    environment:
      FTP_USER: ${FTP_USER}
      FTP_UID: ${FTP_UID}
      FTP_GID: ${FTP_GID}
      FTP_PASV_MIN: ${FTP_PASV_MIN}
      FTP_PASV_MAX: ${FTP_PASV_MAX}
    secrets:
      - ftp_password
    volumes:
      - wp_files:/var/www/html
    networks: [intra]
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 21"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    pull_policy: never
    ports:
      - "127.0.0.1:21:21"
      - "127.0.0.1:${FTP_PASV_MIN}-${FTP_PASV_MAX}:${FTP_PASV_MIN}-${FTP_PASV_MAX}"
  adminer:
    build:
      context: requirements/adminer
      args:
        ALPINE_TAG: ${ALPINE_TAG}
        ADMINER_VERSION: ${ADMINER_VERSION}
    image: adminer:v1
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks: [intra]
    healthcheck:
      test: ["CMD-SHELL", "php-fpm84 -tt >/dev/null 2>&1 && bash -lc 'exec 3<>/dev/tcp/127.0.0.1/9000'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      mariadb:
        condition: service_healthy
    pull_policy: never

  mailpit:
    build:
      context: requirements/mailpit
      args:
        ALPINE_TAG: ${ALPINE_TAG}
        MAILPIT_VERSION: ${MAILPIT_VERSION}
    image: mailpit:v1
    container_name: mailpit
    restart: always
    environment:
      MP_HTTP_ADDR: 0.0.0.0:${MAILPIT_HTTP_PORT}
      MP_SMTP_ADDR: 0.0.0.0:${MAILPIT_SMTP_PORT}
      MP_DATA_FILE: /data/mailpit.db
      MP_WEBROOT: /mail/
    volumes:
      - mailpit_data:/data
    networks: [intra]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${MAILPIT_HTTP_PORT}/mail/ > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    pull_policy: never

networks:
  intra:
    driver: bridge

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind
  wp_files:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/redis
      o: bind
  static_site:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/static-site
      o: bind
  mailpit_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mailpit
      o: bind

secrets:
  wp_db_password:
    file: /home/${LOGIN}/data/secrets/wp_db_password
  mariadb_root_password:
    file: /home/${LOGIN}/data/secrets/mariadb_root_password
  wp_admin_password:
    file: /home/${LOGIN}/data/secrets/wp_admin_password
  wp_user_password:
    file: /home/${LOGIN}/data/secrets/wp_user_password
  redis_password:
    file: /home/${LOGIN}/data/secrets/redis_password
  ftp_password:
    file: /home/${LOGIN}/data/secrets/ftp_password